POST http://localhost:7071/api/workflow_httptrigger HTTP/1.1
Content-Type: application/json

{
    "message": "who is my manager?", 
    "workflow_name": "Main-HR-Agent",
    "parameters": {
        "userid": "JDOE",
        "username": "John Doe"
    }
}


###


POST http://localhost:7071/api/workflow_httptrigger HTTP/1.1
Content-Type: application/json

{
    "message": "and my vacation balance?", 
    "workflow_name": "Main-HR-Agent",
    "parameters": {
        "userid": "JDOE",
        "username": "John Doe"
    },
    "threadid": "conv_77c5ff5988787c1a006WYHFISS34SlRk71W3eQNQmEykRlGWA2"
}

###


POST http://localhost:7071/api/workflow_httptrigger HTTP/1.1
Content-Type: application/json

{
    "message": "what are the health plans you have?", 
    "workflow_name": "Main-HR-Agent",
    "parameters": {
        "userid": "JDOE",
        "username": "John Doe"
    },
    "threadid": ""
}

###


POST http://localhost:7071/api/workflow_httptrigger HTTP/1.1
Content-Type: application/json

{
    "message": "compare them and tell me the differences?", 
    "workflow_name": "Main-HR-Agent",
    "parameters": {
        "userid": "JDOE",
        "username": "John Doe"
    },
    "threadid": "conv_d5e8cfc330357f5600NrUjDs6Y3BT2cTjSi6J1xafSqSdvGjCZ"
}